Repository AstuteSource/chasten, pull requests merged in 2023-10, with the labels that each got.

#53 Add Dockerfile for developers to use to run Chasten
  .gitignore
  Dockerfile
  README.md
Labels: infrastructure

#52 fix: Datasette-serve command not running correctly on Windows
  .chasten/checks.yml
  chasten/database.py
  chasten/main.py
  chasten/util.py
  tests/test_database.py
Labels: bug, ready-for-review

#78 fix: Changed encoding to utf-8 if default fails
  chasten/filesystem.py
Labels: bug

#73 Feature: adds version command to `chasten`
  chasten/main.py
Labels: enhancement, ready-for-review

#68 WIP: Feature: Allow `min` and `max` values in any checks file to have `null` value
  chasten/checks.py
  chasten/results.py
  chasten/validate.py
Labels: infrastructure, ready-for-review

#60 Convert for POSIX file paths
  tests/test_constants.py
  tests/test_filesystem.py
  tests/test_main.py
Labels: test

#70 Syslog added to documentation
  README.md
Labels: documentation, ready-for-review

#95 Restrict and better document the calculation and reporting of coverage
  .github/workflows/build.yml
  tests/test_validate.py
Labels: infrastructure, ready-for-review
