Repository AstuteSource/chasten, pull requests merged in 2023-09, with the labels that each got.

#66 Fix: revert master commits again
  chasten/main.py
  chasten/util.py
  poetry.lock
Labels: bug, in-progress

#48 Added Change to Typer call for help on no argument
  chasten/main.py
Labels: enhancement, in-progress

#64 feat: Workflow now checks more OS
  .github/workflows/build.yml
Labels: enhancement, infrastructure, ready-for-review

#55 Adding the Policies, Documentation, and Templates to Improve Community Standards
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  pull_request_template.md
  security.md
Labels: documentation
